.\" Copyright (c) 2003 Tim Kientzle
.\" Copyright (c) 2005 Andrew Turner
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd September 25, 2005
.Dt libpkg 3
.Os
.Sh NAME
.Nm libpkg
.Nd library for managing binary packages
.Sh LIBRARY
.Lb libpkg
.Sh OVERVIEW
The library provides a set of APIs for locating package
files and managing installed packages.
There are three fundamental concepts:
.Bl -tag -compact -width indent
.It package object
A package object is a handle for an installable package.
You obtain a package object from either the package
repository or package database.
Changes made to an installed package object affect the
package on disk. For example, if you remove a file from the
package object, that causes the corresponding file to be
deleted from disk.
Packages from a repository can be installed to a given
database.
.It package database
A collection of information about installed packages.
In particular, you can ask the package database
for a list of all installed packages or the name of a package
containing a particular file.
.It package repository
A place where package files are stored.
This could be a directory, a CD-ROM, or a remote FTP site.
Some package repositories can provide information
about package dependencies.
.El
Part of the goal is to remove the need for applications to
know anything about the internal details of these systems.
For example, the package database may be implemented as
a collection of files stored in directories, as a Berkeley
DB database file, or as a collection of tables in a relational
database.
.Sh SEE ALSO
.Xr pkg 3 ,
.Xr pkg_repo 3 ,
.Xr pkg_db 3
